---

- name: Manage Deployment for PrometheusExporter {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'deployment.yml.j2') }}"

- name: Manage Service for PrometheusExporter {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    definition: "{{ lookup('template', 'service.yml.j2') }}"

- name: Convert serviceMonitorEnabled boolean var into ansible service_monitor_state state var for PrometheusExporter {{ meta.name }} on Namespace {{ meta.namespace }}
  set_fact:
    service_monitor_state: "present"
  when: service_monitor_enabled|bool == true

- name: Manage ServiceMonitor for PrometheusExporter {{ meta.name }} on Namespace {{ meta.namespace }}
  k8s:
    state: "{{ service_monitor_state }}"
    definition: "{{ lookup('template', 'servicemonitor.yml.j2') }}"
