apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-exporter-elasticsearch-es-staging
data:
  es-exporter.cfg: |
    [DEFAULT]
    # How often to run queries.
    QueryIntervalSecs = 60
    # How long to wait for a query to return before timing out.
    QueryTimeoutSecs = 40
    # The indices to run the query on.
    QueryIndices = _all

    [query_backend_hermes_requests_5xx]
    QueryIntervalSecs = 10
    QueryTimeoutSecs = 15
    QueryIndices = <backend-{now/d{YYYY-MM-dd}}>
    QueryJson = {
            "size": 0,
            "query": {
                "filtered": {
                    "query": {
                        "query_string": {
                            "query": "http_status_code:>499 AND host: hermes*"
                        }
                    }
                }
            }
        }
