apiVersion: ops.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: es-staging
spec:
  type: "elasticsearch"
  serviceMonitorEnabled: true
  grafanaDashboardEnabled: false
  dbHost: "http://logging-es.openshift-logging.svc"
  dbPort: "9200"
