apiVersion: ops.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: es-staging
spec:
  type: "elasticsearch"
  serviceMonitorState: "present"
  serviceMonitorLabelKey: "monitoring-key"
  serviceMonitorLabelValue: "middleware"
  dbHost: "http://logging-es.openshift-logging.svc"
  dbPort: "9200"
  configurationConfigmapName: "prometheus-exporter-elasticsearch-es-staging"
