apiVersion: monitoring.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: staging-es
spec:
  type: es
  grafanaDashboard:
    label:
      key: discovery
      value: enabled
  dbHost: https://vpc-staging-es.us-east-1.es.amazonaws.com
  dbPort: 443
