apiVersion: monitoring.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: staging-zync-postgresql
spec:
  type: postgresql
  grafanaDashboard:
    label:
      key: monitoring-key
      value: middleware
  extraLabel:
    key: threescale_component
    value: zync
  dbConnectionStringSecretName: prometheus-exporter-postgresql-staging-zync-postgresql
