---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-server
spec:
  selector:
    matchLabels:
      app: redis-server
  serviceName: redis-server
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
        - name: redis-server
          image: redis:6.2.6
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 6379
              name: redis-server
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
              - redis-cli
              - ping
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
              - redis-cli
              - ping
---
apiVersion: v1
kind: Service
metadata:
  name: backend-redis
  labels:
    app: redis-server
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-server
  selector:
    app: redis-server
---
apiVersion: v1
kind: Service
metadata:
  name: system-redis
  labels:
    app: redis-server
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-server
  selector:
    app: redis-server
