apiVersion: monitoring.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: staging-system-redis
spec:
  type: redis
  grafanaDashboard:
    label:
      key: monitoring-key
      value: middleware
  extraLabel:
    key: threescale_component
    value: system
  dbHost: system-redis
  dbPort: 6379
  dbCheckKeys: "db1=queue:backend_sync,db1=queue:billing,db1=queue:critical,db1=queue:default,db1=queue:deletion,db1=queue:events,db1=queue:low,db1=queue:priority,db1=queue:web_hooks,db1=queue:zync"
