{
 "title": "PrometheusExporter CloudWatch",
 "description": "Dashboard for AWS Cloudwatch Statistics",
 "tags": [
  "prometheus-exporter",
  "cloudwatch"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "prometheus_exporter",
    "label": "Prometheus Exporter",
    "query": "label_values(cloudwatch_exporter_scrape_duration_seconds,prometheus_exporter)"
   }
  ]
 },
 "panels": [
  { "title": "Exporter Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Potential monthly bill (projection based on the last hour)",
   "type": "gauge",
   "description": "Assumption of $10 per 1M calls",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(sum(increase(cloudwatch_requests_total{prometheus_exporter=\"$prometheus_exporter\"}[1h])) * 24) * 30 * 10 / 1000000"
    }
   ]
  },
  {
   "title": "Exporter scrape duration (seconds)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(cloudwatch_exporter_scrape_duration_seconds{prometheus_exporter=\"stg-saas-cw\"}) by (prometheus_exporter)"
    }
   ]
  },
  {
   "title": "Exporter scrape duration evolution (seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "cloudwatch_exporter_scrape_duration_seconds{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ prometheus_exporter }}"
    }
   ]
  },
  {
   "title": "Exporter scrape errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(cloudwatch_exporter_scrape_error{prometheus_exporter=\"stg-saas-cw\"}) by (prometheus_exporter)"
    }
   ]
  },
  {
   "title": "API Call count (last 5 minutes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cloudwatch_requests_total{prometheus_exporter=\"$prometheus_exporter\"}[5m]))",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "sum(increase(cloudwatch_requests_total{prometheus_exporter=\"$prometheus_exporter\"}[5m])) by (exported_namespace)",
     "legendFormat": "{{ exported_namespace }}"
    }
   ]
  },
  {
   "title": "API Call Count - Comparison (last 5 minutes)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(cloudwatch_requests_total{prometheus_exporter=\"$prometheus_exporter\"}[5m])) by (exported_namespace)",
     "legendFormat": "{{ exported_namespace }}"
    }
   ]
  },
  { "title": "AWS ElastiCache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Utilization Average (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_cpuutilization_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ cache_cluster_id }}"
    }
   ]
  },
  {
   "title": "Current Connections Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_curr_connections_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ cache_cluster_id }}"
    }
   ]
  },
  {
   "title": "Freeable Memory Average (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_freeable_memory_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ cache_cluster_id }}"
    }
   ]
  },
  {
   "title": "Swap Usage Average (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_swap_usage_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ cache_cluster_id }}"
    }
   ]
  },
  {
   "title": "Network Bytes In Average (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_network_bytes_in_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ cache_cluster_id }}"
    }
   ]
  },
  {
   "title": "Network Bytes Out Average (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_network_bytes_out_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ cache_cluster_id }}"
    }
   ]
  },
  {
   "title": "Current Items Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_curr_items_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ cache_cluster_id }}"
    }
   ]
  },
  {
   "title": "Evictions Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elasticache_evictions_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ cache_cluster_id }}"
    }
   ]
  },
  { "title": "AWS RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "CPU Utilization Average (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ dbinstance_identifier }}"
    }
   ]
  },
  {
   "title": "Database Connections Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_database_connections_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ dbinstance_identifier }}"
    }
   ]
  },
  {
   "title": "Freeable Memory Average (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_freeable_memory_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ dbinstance_identifier }}"
    }
   ]
  },
  {
   "title": "Free Storage Space Average (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_free_storage_space_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ dbinstance_identifier }}"
    }
   ]
  },
  { "title": "AWS Application Load Balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Healthy Host Count Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_healthy_host_count_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ target_group }}"
    }
   ]
  },
  {
   "title": "Unhealthy Host Count Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_un_healthy_host_count_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ target_group }}"
    }
   ]
  },
  {
   "title": "Request Count Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_request_count_sum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ load_balancer }}"
    }
   ]
  },
  {
   "title": "Target Response Time Average (seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_target_response_time_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ target_group }}"
    }
   ]
  },
  {
   "title": "HTTP Code Target 2XX Count Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_httpcode_target_2_xx_count_sum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ target_group }}"
    }
   ]
  },
  {
   "title": "HTTP Code Target 5XX Count Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_httpcode_target_5_xx_count_sum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ target_group }}"
    }
   ]
  },
  {
   "title": "HTTP Code Target 3XX Count Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_httpcode_target_3_xx_count_sum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ target_group }}"
    }
   ]
  },
  {
   "title": "HTTP Code Target 4XX Count Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_httpcode_target_4_xx_count_sum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ target_group }}"
    }
   ]
  },
  { "title": "AWS Network Load Balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Healthy Host Count Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_networkelb_healthy_host_count_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ target_group }}"
    }
   ]
  },
  {
   "title": "Unhealthy Host Count Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_networkelb_un_healthy_host_count_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ target_group }}"
    }
   ]
  },
  {
   "title": "Active Flow Count Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_networkelb_active_flow_count_sum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ load_balancer }}"
    }
   ]
  },
  {
   "title": "New Flow Count Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_networkelb_new_flow_count_sum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ load_balancer }}"
    }
   ]
  },
  { "title": "AWS Classic Load Balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Healthy Host Count Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elb_healthy_host_count_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ load_balancer_name }}"
    }
   ]
  },
  {
   "title": "Unhealthy Host Count Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elb_un_healthy_host_count_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ load_balancer_name }}"
    }
   ]
  },
  {
   "title": "Request Count Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elb_request_count_sum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ load_balancer_name }}"
    }
   ]
  },
  {
   "title": "Latency Average (seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aws_elb_latency_average{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ load_balancer_name }}"
    }
   ]
  },
  {
   "title": "HTTP Code Backend 2XX Count Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elb_httpcode_backend_2_xx_sum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ load_balancer_name }}"
    }
   ]
  },
  {
   "title": "HTTP Code Backend 5XX Count Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elb_httpcode_backend_5_xx_sum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ load_balancer_name }}"
    }
   ]
  },
  {
   "title": "HTTP Code Backend 3XX Count Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elb_httpcode_backend_3_xx_sum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ load_balancer_name }}"
    }
   ]
  },
  {
   "title": "HTTP Code Backend 4XX Count Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_elb_httpcode_backend_4_xx_sum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ load_balancer_name }}"
    }
   ]
  },
  { "title": "AWS ElasticSearch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 } },
  {
   "title": "Cluster Status GREEN Maximum",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 152 },
   "targets": [
    {
     "expr": "aws_es_cluster_status_green_maximum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ domain_name }}"
    }
   ]
  },
  {
   "title": "Cluster Status YELLOW Maximum",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 152 },
   "targets": [
    {
     "expr": "aws_es_cluster_status_yellow_maximum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ domain_name }}"
    }
   ]
  },
  {
   "title": "Cluster Status RED Maximum",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 152 },
   "targets": [
    {
     "expr": "aws_es_cluster_status_red_maximum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ domain_name }}"
    }
   ]
  },
  {
   "title": "Automated Snapshot Failure Maximum",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 152 },
   "targets": [
    {
     "expr": "aws_es_automated_snapshot_failure_maximum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ domain_name }}"
    }
   ]
  },
  {
   "title": "Cluster Number Nodes Maximum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aws_es_nodes_maximum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ domain_name }}"
    }
   ]
  },
  {
   "title": "Free Storage Space Minimum (megabytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "aws_es_free_storage_space_minimum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ domain_name }}"
    }
   ]
  },
  {
   "title": "CPU Utilization Maximum (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_es_cpuutilization_maximum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ domain_name }}"
    }
   ]
  },
  {
   "title": "JVM Memory Pressure Maximum (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_es_jvmmemory_pressure_maximum{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ domain_name }}"
    }
   ]
  }
 ]
}