{
 "title": "PrometheusExporter Memcached",
 "description": "Dashboard for Memcached Statistics",
 "tags": [
  "prometheus-exporter",
  "memcached"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "prometheus_exporter",
    "label": "Prometheus Exporter",
    "query": "label_values(memcached_up,prometheus_exporter)"
   },
   { "name": "interval", "label": "interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "memcached_up{prometheus_exporter=\"$prometheus_exporter\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "memcached_uptime_seconds{prometheus_exporter=\"$prometheus_exporter\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "memcached_version{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "% Hit ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_commands_total{prometheus_exporter=\"$prometheus_exporter\",status=\"miss\"})  / sum (memcached_commands_total{prometheus_exporter=\"$prometheus_exporter\"}) ",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memcached_current_connections{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Get / Set ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_commands_total{prometheus_exporter=\"$prometheus_exporter\",command=\"set\"}) / sum (memcached_commands_total{prometheus_exporter=\"$prometheus_exporter\",command=\"get\"})",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_commands_total{prometheus_exporter=\"$prometheus_exporter\"}) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "evicts / reclaims",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(memcached_items_evicted_total{prometheus_exporter=\"$prometheus_exporter\"})",
     "legendFormat": "evicts"
    },
    {
     "expr": "sum(memcached_items_reclaimed_total{prometheus_exporter=\"$prometheus_exporter\"})",
     "legendFormat": "reclaims"
    }
   ]
  },
  {
   "title": "Read / written bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(memcached_read_bytes_total{prometheus_exporter=\"$prometheus_exporter\"}[$interval]))",
     "legendFormat": "read from network"
    },
    {
     "expr": "irate(memcached_written_bytes_total{prometheus_exporter=\"$prometheus_exporter\"}[$interval])",
     "legendFormat": "written to network"
    }
   ]
  },
  {
   "title": "Total memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(memcached_current_bytes{prometheus_exporter=\"$prometheus_exporter\"}) / sum(memcached_limit_bytes{prometheus_exporter=\"$prometheus_exporter\"})",
     "legendFormat": "% used memory used"
    }
   ]
  },
  {
   "title": "Items in cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_current_items{prometheus_exporter=\"$prometheus_exporter\"})",
     "legendFormat": "items "
    }
   ]
  }
 ]
}