{
 "title": "PrometheusExporter Sphinx",
 "description": "Dashboard for Sphinx Statistics",
 "tags": [
  "prometheus-exporter",
  "sphinx"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "prometheus_exporter",
    "label": "Prometheus Exporter",
    "query": "label_values(sphinx_up, prometheus_exporter)"
   },
   { "name": "interval", "label": "interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Sphinx Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sphinx_up{prometheus_exporter=\"$prometheus_exporter\"}"
    }
   ]
  },
  {
   "title": "Sphinx Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sphinx_uptime{prometheus_exporter=\"$prometheus_exporter\"}"
    }
   ]
  },
  {
   "title": "Sphinx Threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(sphinx_threads_count{prometheus_exporter=\"$prometheus_exporter\"})"
    }
   ]
  },
  {
   "title": "Sphinx Queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "rate(sphinx_queries{prometheus_exporter=\"$prometheus_exporter\"}[$interval]) or irate(sphinx_queries{prometheus_exporter=\"$prometheus_exporter\"}[$interval])"
    }
   ]
  },
  {
   "title": "Sphinx Avg query time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "(sphinx_query_wall{prometheus_exporter=\"$prometheus_exporter\"} / sphinx_queries{prometheus_exporter=\"$prometheus_exporter\"})*1000"
    }
   ]
  },
  {
   "title": "Sphinx Indexes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sphinx_index_count{prometheus_exporter=\"$prometheus_exporter\"}"
    }
   ]
  },
  {
   "title": "Command Operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "rate(sphinx_command_delete{prometheus_exporter=\"$prometheus_exporter\"}[$interval]) or irate(sphinx_command_delete{prometheus_exporter=\"$prometheus_exporter\"}[5m])",
     "legendFormat": "Delete"
    },
    {
     "expr": "rate(sphinx_command_flushattrs{prometheus_exporter=\"$prometheus_exporter\"}[$interval]) or irate(sphinx_command_flushattrs{prometheus_exporter=\"$prometheus_exporter\"}[5m])",
     "legendFormat": "Flushattrs"
    },
    {
     "expr": "rate(sphinx_command_keywords{prometheus_exporter=\"$prometheus_exporter\"}[$interval]) or irate(sphinx_command_keywords{prometheus_exporter=\"$prometheus_exporter\"}[5m])",
     "legendFormat": "Keywords"
    },
    {
     "expr": "rate(sphinx_command_persist{prometheus_exporter=\"$prometheus_exporter\"}[$interval]) or irate(sphinx_command_persist{prometheus_exporter=\"$prometheus_exporter\"}[5m])",
     "legendFormat": "Persist"
    },
    {
     "expr": "rate(sphinx_command_search{prometheus_exporter=\"$prometheus_exporter\"}[$interval]) or irate(sphinx_command_search{prometheus_exporter=\"$prometheus_exporter\"}[5m])",
     "legendFormat": "Search"
    },
    {
     "expr": "rate(sphinx_command_status{prometheus_exporter=\"$prometheus_exporter\"}[$interval]) or irate(sphinx_command_status{prometheus_exporter=\"$prometheus_exporter\"}[5m])",
     "legendFormat": "Status"
    },
    {
     "expr": "rate(sphinx_command_update{prometheus_exporter=\"$prometheus_exporter\"}[$interval]) or irate(sphinx_command_update{prometheus_exporter=\"$prometheus_exporter\"}[5m])",
     "legendFormat": "Update"
    }
   ]
  },
  {
   "title": "Sphinx Indexed documents",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sphinx_indexed_documents{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Sphinx Indexed bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sphinx_indexed_bytes{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Sphinx Indexes RAM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sphinx_ram_bytes{prometheus_exporter=\"$prometheus_exporter\"}",
     "legendFormat": "{{index}}"
    }
   ]
  }
 ]
}