apiVersion: ops.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: staging-system-sphinx
spec:
  type: sphinx
  grafanaDashboard:
    label:
      key: monitoring-key
      value: middleware
  extraLabel:
    key: threescale_component
    value: system
  dbHost: system-sphinx
  dbPort: 9306
