apiVersion: ops.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: system-mysql-staging
spec:
  type: "mysql"
  serviceMonitorEnabled: true
  grafanaDashboardEnabled: true
  grafanaDashboardLabelKey: "monitoring-key"
  grafanaDashboardLabelValue: "middleware"
  labelCustomKey: "threescale_component"
  labelCustomValue: "system"
  dbConnectionStringSecretName: "prometheus-exporter-mysql-system-mysql-staging"
