apiVersion: ops.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: staging-system-mysql
spec:
  type: mysql
  grafanaDashboard:
    label:
      key: monitoring-key
      value: middleware
  extraLabel:
    key: threescale_component
    value: system
  dbConnectionStringSecretName: prometheus-exporter-mysql-staging-system-mysql
