---

## Main
type: "none" # memcached, redis, mysql, postgresql, sphinx, elasticsearch, cloudwatch

## ServiceMonitor config
service_monitor_state: "absent" # Or "present"  (ansible state var)
service_monitor_interval: "30s"

## Generic config
## Optional, if you want to add a custom label to resources, you can choose a custom key/value. Example for 3scale:
#label_custom_key": "threescale_component"
#label_custom_value: "zync" # system, backend, zync, keycloak...
