version: 2.1
workflows:
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - release-master:
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
commands:
  docker-login:
    steps:
      - run:
          name: Docker login
          command: |
            docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" quay.io
  install-operator-sdk:
    steps:
      - run:
          name: Install operator-sdk
          command: |
            export OPERATOR_SDK_RELEASE_VERSION=v0.18.1
            curl -OJL https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_RELEASE_VERSION}/operator-sdk-${OPERATOR_SDK_RELEASE_VERSION}-x86_64-linux-gnu
            chmod +x operator-sdk-${OPERATOR_SDK_RELEASE_VERSION}-x86_64-linux-gnu && sudo cp operator-sdk-${OPERATOR_SDK_RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${OPERATOR_SDK_RELEASE_VERSION}-x86_64-linux-gnu

  build-push-operator-image:
    steps:
      - checkout
      - docker-login
      - install-operator-sdk
      - run:
          name: Build and Push Operator Image
          command: |
              make operator-image-update VERSION=${CIRCLE_TAG:-master}

jobs:
  release:
    machine:
      image: circleci/classic:latest
    steps:
      - build-push-operator-image
  release-master:
    machine:
      image: circleci/classic:latest
    steps:
      - build-push-operator-image
