apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prometheusexporters.ops.3scale.net
spec:
  group: ops.3scale.net
  names:
    kind: PrometheusExporter
    listKind: PrometheusExporterList
    plural: prometheusexporters
    singular: prometheusexporter
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
