---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-exporter-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus-exporter-operator
  template:
    metadata:
      labels:
        name: prometheus-exporter-operator
    spec:
      serviceAccountName: prometheus-exporter-operator
      containers:
        - name: prometheus-exporter-operator
          image: "REPLACE_IMAGE"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "prometheus-exporter-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: runner
          emptyDir: {}
