apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-exporter-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus-exporter-operator
  template:
    metadata:
      labels:
        name: prometheus-exporter-operator
    spec:
      serviceAccountName: prometheus-exporter-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: "quay.io/3scale/prometheus-exporter-operator:v1.0.0"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: "quay.io/3scale/prometheus-exporter-operator:v1.0.0"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "prometheus-exporter-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
