apiVersion: monitoring.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: staging-system-searchd
spec:
  type: manticore
  grafanaDashboard:
    label:
      key: discovery
      value: enabled
  extraLabel:
    key: threescale_component
    value: system
  dbHost: system-searchd
  dbPort: 9306
