# Adds namespace to all resources.
namespace: default

namePrefix: prometheus-exporter-operator-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

patchesStrategicMerge:
- debug_logs_patch.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../crd
- ../rbac
- ../manager
- external-apis/servicemonitors.monitoring.coreos.com.yaml
- external-apis/grafanadashboards.integreatly.org.yaml
images:
- name: testing
  newName: testing-operator

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/2
        value: { "name": "WATCH_NAMESPACE", "value": default }