apiVersion: monitoring.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: production
spec:
  type: sendgrid
  grafanaDashboard:
    label:
      key: discovery
      value: enabled
  sendgridCredentialsSecretName: prometheus-exporter-sendgrid-production
