apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-exporter-cloudwatch
spec:
  groups:
    - name: prometheus-exporter-cloudwatch.rules
      rules:
      - alert: AWSElastiCacheCPUHigh
        expr: aws_elasticache_cpuutilization_average > 80
        for: 5m
        labels:
          severity: critical
        annotations:
          message: "AWS ElastiCache instance {{ $labels.cache_cluster_id }} from {{ $labels.prometheus_exporter }} has High CPU usage (%)"
      - alert: AWSElastiCacheFreeableMemoryLow
        expr: aws_elasticache_freeable_memory_average < 1000000000
        for: 2m
        labels:
          severity: critical
        annotations:
          message: "AWS ElastiCache instance {{ $labels.cache_cluster_id }} from {{ $labels.prometheus_exporter }} has Low Freeable Memory usage (bytes)"
      - alert: AWSElastiCacheSwapMemoryHigh
        expr: aws_elasticache_swap_usage_average > 250000000
        for: 2m
        labels:
          severity: critical
        annotations:
          message: "AWS ElastiCache instance {{ $labels.cache_cluster_id }} from {{ $labels.prometheus_exporter }} has High Swap Memory usage (bytes)"
      - alert: AWSElastiCacheEvictionsHigh
        expr: aws_elasticache_evictions_average > 500
        for: 2m
        labels:
          severity: critical
        annotations:
          message: "AWS ElastiCache instance {{ $labels.cache_cluster_id }} from {{ $labels.prometheus_exporter }} has High number of Evictions"
      - alert: AWSRDSCPUHigh
        expr: aws_rds_cpuutilization_average > 80
        for: 5m
        labels:
          severity: critical
        annotations:
          message: "AWS RDS instance {{ $labels.dbinstance_identifier }} from {{ $labels.prometheus_exporter }} has High CPU usage (%)"
      - alert: AWSRDSFreeableMemoryLow
        expr: aws_rds_freeable_memory_average < 1000000000
        for: 2m
        labels:
          severity: critical
        annotations:
          message: "AWS RDS instance {{ $labels.dbinstance_identifier }} from {{ $labels.prometheus_exporter }} has Low Freeable Memory usage (bytes)"
      - alert: AWSRDSFreeStorageSpaceLow
        expr: aws_rds_free_storage_space_average < 5000000000
        for: 2m
        labels:
          severity: critical
        annotations:
          message: "AWS RDS instance {{ $labels.dbinstance_identifier }} from {{ $labels.prometheus_exporter }} has Low Free Storage Space usage (bytes)"
      - alert: AWSElasticsearchClusterStatusYellow
        expr: aws_es_cluster_status_yellow_maximum == 1
        for: 5m
        labels:
          severity: warning
        annotations:
          message: "AWS Elasticsearch {{ $labels.domain_name }} from {{ $labels.prometheus_exporter }} cluster status is Yellow"
      - alert: AWSElasticsearchClusterStatusRed
        expr: aws_es_cluster_status_red_maximum == 1
        for: 5m
        labels:
          severity: critical
        annotations:
          message: "AWS Elasticsearch {{ $labels.domain_name }} from {{ $labels.prometheus_exporter }} cluster status is Red"
      - alert: AWSElasticsearchAutomaticSnapshotFailed
        expr: aws_es_automated_snapshot_failure_maximum == 1
        for: 5m
        labels:
          severity: critical
        annotations:
          message: "AWS Elasticsearch {{ $labels.domain_name }} from {{ $labels.prometheus_exporter }} has failed its automated snapshot"
      - alert: AWSElasticsearchFreeSpaceDataTotalLow
        expr: aws_es_free_storage_space_sum < 1000000
        for: 5m
        labels:
          severity: critical
        annotations:
          message: "AWS Elasticsearch {{ $labels.domain_name }} from {{ $labels.prometheus_exporter }} has Low Data Total Free Storage Space (megabytes)"
      - alert: AWSElasticsearchFreeSpaceDataNodeLow
        expr: aws_es_free_storage_space_minimum < 100000
        for: 5m
        labels:
          severity: critical
        annotations:
          message: "AWS Elasticsearch {{ $labels.domain_name }} from {{ $labels.prometheus_exporter }} has Low Data Node Free Storage Space (megabytes)"
      - alert: AWSClientVPNCrlDaysToExpiry
        expr: max_over_time(aws_clientvpn_crl_days_to_expiry_average[10m]) < 2
        for: 5m
        labels:
          severity: warning
        annotations:
          message: "AWS ClientVPN CRL {{ $labels.endpoint }} will expire soon, maybe it is not being regenerated"
