apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-exporter-es
spec:
  groups:
    - name: prometheus-exporter-es.rules
      rules:
        # Cluster status alerts
        - alert: ElasticsearchDown
          expr: elasticsearch_cluster_health_up == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            message: "Elasticsearch {{ $labels.prometheus_exporter }} is DOWN"
        - alert: ElasticsearchClusterStatusYellow
          expr: elasticsearch_cluster_health_status {color="yellow"} == 1
          for: 1m
          labels:
            severity: warning
          annotations:
            message: "Elasticsearch {{ $labels.prometheus_exporter }} Cluster Status is Yellow"
        - alert: ElasticsearchClusterStatusRed
          expr: elasticsearch_cluster_health_status {color="red"} == 1
          for: 1m
          labels:
            severity: critical
          annotations:
            message: "Elasticsearch {{ $labels.prometheus_exporter }} Cluster Status is Red"

        # Memory alerts
        - alert: ElasticsearchNodeHeapMemoryHigh
          expr: 100* elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"} > 85
          for: 10m
          labels:
            severity: warning
          annotations:
            message: "Elasticsearch node {{ $labels.name }} Heap Memory usage is High"
        - alert: ElasticsearchNodeHeapMemoryHigh
          expr: 100* elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"} > 95
          for: 10m
          labels:
            severity: critical
          annotations:
            message: "Elasticsearch node {{ $labels.name }} Heap Memory usage is High"

        - alert: ElasticsearchNodeFreeSpaceLow
          expr: 100 -( 100 * (elasticsearch_filesystem_data_size_bytes - elasticsearch_filesystem_data_free_bytes)/ elasticsearch_filesystem_data_size_bytes) < 15
          for: 10m
          labels:
            severity: warning
          annotations:
            message: "Elasticsearch node {{ $labels.name }} has Low Free space"
        - alert: ElasticsearchNodeFreeSpaceLow
          expr: 100 -( 100 * (elasticsearch_filesystem_data_size_bytes - elasticsearch_filesystem_data_free_bytes)/ elasticsearch_filesystem_data_size_bytes) < 5
          for: 10m
          labels:
            severity: critical
          annotations:
            message: "Elasticsearch node {{ $labels.name }} has Low Free space"

        - alert: ElasticsearchWillFillIn96h
          expr: predict_linear(elasticsearch_filesystem_data_free_bytes{}[24h], 96 * 3600) < 0
          for: 1h
          labels:
            severity: warning
          annotations:
            message: "Elasticsearch node {{ $labels.name }} will fill in 4 days"
        - alert: ElasticsearchNodeWillFillIn24h
          expr: predict_linear(elasticsearch_filesystem_data_free_bytes{}[24h], 24 * 3600) < 0
          for: 1h
          labels:
            severity: critical
          annotations:
            message: "Elasticsearch node {{ $labels.name }} will fill in 24h"

        # CPU alerts
        - alert: ElasticSeachNodeHighCPU
          expr: elasticsearch_os_cpu_percent > 85
          for: 10m
          labels:
            severity: warning
          annotations:
            message: "Elasticsearch node {{ $labels.name }} has high CPU usage"
        - alert: ElasticSeachNodeHighCPU
          expr: elasticsearch_os_cpu_percent > 95
          for: 10m
          labels:
            severity: critical
          annotations:
            message: "Elasticsearch node {{ $labels.name }} has high CPU usage"