apiVersion: ops.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: staging-system-memcached
spec:
  type: memcached
  grafanaDashboard:
    label:
      key: monitoring-key
      value: middleware
  extraLabel:
    key: threescale_component
    value: system
  dbHost: system-memcache
  dbPort: 11211
