apiVersion: ops.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: system-memcached-staging
spec:
  type: "memcached"
  serviceMonitorState: "present"
  labelCustomKey: "threescale_component"
  labelCustomValue: "system"
  dbHost: "system-memcache"
  dbPort: "11211"
