apiVersion: monitoring.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: staging-system-memcached
spec:
  type: memcached
  grafanaDashboard:
    label:
      key: discovery
      value: enabled
  extraLabel:
    key: threescale_component
    value: system
  dbHost: system-memcache
  dbPort: 11211
