apiVersion: monitoring.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: staging-aws-cw
spec:
  type: cloudwatch
  grafanaDashboard:
    label:
      key: discovery
      value: enabled
  awsCredentialsSecretName: prometheus-exporter-cloudwatch-staging-aws-cw
  configurationConfigmapName: prometheus-exporter-cloudwatch-staging-aws-cw
