apiVersion: ops.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: aws-staging
spec:
  type: "cloudwatch"
  serviceMonitorState: "present"
  serviceMonitorLabelKey: "monitoring-key"
  serviceMonitorLabelValue: "middleware"
  labelEnvironment: "staging"
  resourcesLimitsMemory: "256Mi"
  awsCredentialsSecretName: "prometheus-exporter-cloudwatch-aws-staging"
  configurationConfigmapName: "prometheus-exporter-cloudwatch-aws-staging"
