apiVersion: ops.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: aws-staging
spec:
  type: "cloudwatch"
  serviceMonitorEnabled: true
  grafanaDashboardEnabled: true
  grafanaDashboardLabelKey: "monitoring-key"
  grafanaDashboardLabelValue: "middleware"
  resourcesLimitsMemory: "256Mi"
  awsCredentialsSecretName: "prometheus-exporter-cloudwatch-aws-staging"
  configurationConfigmapName: "prometheus-exporter-cloudwatch-aws-staging"
