apiVersion: monitoring.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: staging-blackbox
spec:
  type: probe
  grafanaDashboard:
    label:
      key: monitoring-key
      value: middleware
  configurationConfigmapName: prometheus-exporter-probe-staging-blackbox
