# In case you don't want to use a Configmap for the blackbox modules config.yml because it might contain sensitive data like keys...
# you can use a Secret instead, and so specify the Secret name on CR field configurationSecretName (instead of using configurationConfigmapName)
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-exporter-probe-staging-blackbox
stringData:
  config.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          method: GET
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: false
          tls_config:
            insecure_skip_verify: false
          preferred_ip_protocol: "ip4" # defaults to "ip6"
          ip_protocol_fallback: false  # no fallback to "ip6"
      tcp_connect:
        prober: tcp
        timeout: 5s