---

# Exporter
prometheus_exporter_port: 9200
prometheus_exporter_image: "braedon/prometheus-es-exporter"
prometheus_exporter_version: "0.4.3"

# Custom
db_host: "http://logging-es.openshift-logging.svc"
db_port: "9200"
configuration_configmap_name: "prometheus-exporter-{{ type }}-{{ meta.name }}"

###### Example of ConfigMap
#
# If you don't specify CR field configurationConfigmapName, it will be used default ConfigMap name "prometheus-exporter-elasticsearch-{{ CR_NAME }}"
#
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: prometheus-exporter-elasticsearch-example-es
#data:
#  es-exporter.cfg: |
#    [DEFAULT]
#    # How often to run queries.
#    QueryIntervalSecs = 60
#    # How long to wait for a query to return before timing out.
#    QueryTimeoutSecs = 40
#    # The indices to run the query on.
#    QueryIndices = _all
#
#    [query_backend_hermes_requests_5xx]
#    QueryIntervalSecs = 10
#    QueryTimeoutSecs = 15
#    QueryIndices = <backend-{now/d{YYYY-MM-dd}}>
#    QueryJson = {
#            "size": 0,
#            "query": {
#                "filtered": {
#                    "query": {
#                        "query_string": {
#                            "query": "http_status_code:>499 AND host: hermes*"
#                        }
#                    }
#                }
#            }
#        }
